# -*- coding: utf-8 -*-
"""Image_recognition_code.ipynb

Automatically generated by Colaboratory.


TOP CLASS IMAGE RECOGNITION PROJECT

Step1 : Importing libraries
"""

import keras
from keras.datasets import cifar10
from keras.layers import Dense,Conv2D,MaxPooling2D,Dropout,Flatten
from keras.models import Sequential
from pathlib import Path
from keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

"""Hi there,

Full project code is longer.

For Full Project Code, Project Report and PPT.

Mail me now at vatshayan007@gmail.com
"""

